---
- name: Backup Container
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
  tasks:
    - name: Creating backup.conf configmap
      template:
        src: "templates/cm_backup_conf.yaml.j2"
        dest: "{{ output_path }}/cm_backup_conf.yaml"
    - name: Applying configmap
      shell: oc -n {{ namespace }} apply -f "{{ output_path }}/cm_backup_conf.yaml"
