---
- name: Create output directory if it does not exist
  file:
    path: "{{ output_path }}/just-ask"
    state: directory
    mode: '0755'
- name: Generate manifests
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ output_path }}/just-ask/{{ item }}"
  with_items:
    - deployment_web.yaml
    - service_web.yaml
    - cm_app_config_web.yaml
    - route_web.yaml

- name: Apply Manifests
  shell: oc apply -f {{ output_path }}/just-ask/{{ item }} -n {{ namespace }}
  with_items:
    - deployment_web.yaml
    - service_web.yaml
    - cm_app_config_web.yaml
    - route_web.yaml