app_name: just-ask
web:
  name: just-ask-web
  image_name: plat-gen-docker-local/just-ask-web
  image_tag: 'DEVXT-1720'
  image_registry: 'artifacts.developer.gov.bc.ca'
  artifact_id: 'qaacfs'
  port: "2015"
